config/routes.rb
Notebook::Application.routes.draw do

  resources :notes

  root to: "notes#index"

  get '/mockup' => 'pages#mockup'

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.js
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def mockup
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container" class="notepad">

  <header>
      <div id="theme_links">
          <%= link_to 'Legal Pad', '#', :id => 'legalpad_link' %>
          |
    <%= link_to "Notepad", '#', :id => 'notepad_link' %>
  </div>
  <h1>
    <%= link_to image_tag('bulb.jpg', :size => '75x100'), root_url %>
    <%= link_to 'Aha! Notebook', root_url %>
  </h1>
</header>

  <section>
      <%= yield %>
  </section>


</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_note_row.html.erb
<li id="note_<%= note.id %>" class="note" data-nid="<%= note.id %>">
  <%= note.content %>

  <%= link_to image_tag('trash-can-icon.jpg', height: 20),
              note_url(note), method: 'delete', remote: true %>

  <a href="#"><img src="/assets/pencil.png" height="20" width="20"></a>
</li>

app/views/notes/create.js.erb
<% publish_to "/notes/new" do %>
  //In here we write JS for any subscribed browsers to execute
  $("ul").append("<%= j(render('note_row', :note => @note)) %>");
<% end %>
$("#note_content").val("");

app/views/notes/destroy.js.erb
<% publish_to "/notes/destroy" do %>
  $("#note_<%= @note.id %>").slideUp();
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<div id="trash" style="width: 100%; height: 200px; border: thin red solid">
</div>

<ul>

<% @notes.each do |n| %>
  <%= render 'note_row', :note => n %>
<% end %>

</ul>

<%= form_for(Note.new, remote: true ) do |f| %>
    <%= f.text_field :content, placeholder: 'Add a new aha! here' %>
<% end %>

<%= subscribe_to "/notes/new" %>
<%= subscribe_to "/notes/destroy" %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @note.content %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/pages/mockup.html.erb
<ul>
  <li>Rails Models are Ruby classes intended to represent real-world things.<a href="#"><img src="/assets/trash-can-icon.jpg" height="20" width="20"></a><a href="#"><img src="/assets/pencil.png" height="20" width="20"></a></li>
  <li>Instance variables in controllers hold data for the views.<a href="#"><img src="/assets/trash-can-icon.jpg" height="20" width="20"></a><a href="#"><img src="/assets/pencil.png" height="20" width="20"></a></li>
  <li>Rails is best for database-backed web applications.<a href="#"><img src="/assets/trash-can-icon.jpg" height="20" width="20"></a><a href="#"><img src="/assets/pencil.png" height="20" width="20"></a></li>
  <li>Javascript is pretty cool. <a href="#"><img src="/assets/trash-can-icon.jpg" height="20" width="20"></a><a href="#"><img src="/assets/pencil.png" height="20" width="20"></a></li>
  <li>Pairing accelerates learning.<a href="#"><img src="/assets/trash-can-icon.jpg" height="20" width="20"></a><a href="#"><img src="/assets/pencil.png" height="20" width="20"></a></li>
  <input placeholder="Add a new aha! here" size="50">
</ul>